Pandas is a fast powerful,flexible and easy to use open source data analysis and manupulation tool ,
build on top of the python programming language.
2008 , Mickimey
very well with Structured data

In [2]:
import pandas as pd
df =pd.read_csv('services_data.csv')
df

,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
0,1,101,2001,Food Assistance,Low income families,Income below poverty line,0,active,No wait,San Mateo,4.2
1,2,102,2002,Job Training,Unemployed adults,18+ age,50,active,2 weeks,Daly City,4.5
2,3,103,2003,Senior Care,Senior citizens,Age 60+,20,active,1 week,Redwood City,4.0
3,4,104,2004,Health Checkup,General public,NaN,10,active,3 days,Belmont,3.8
4,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3
5,6,106,2006,Housing Assistance,Homeless individuals,NaN,0,inactive,No wait,San Mateo,4.1
6,7,107,2007,Mental Health Counseling,Adults 18+,Appointment required,30,active,5 days,Daly City,4.6
7,8,108,2008,Legal Aid,Low income residents,Income verification,0,active,1 week,Redwood City,4.4
8,9,109,2009,Drug Rehabilitation,Adults 21+,Medical assessment,100,active,3 weeks,Belmont,3.9
9,10,110,2010,Community Meals,Senior citizens,Age 60+,5,active,No wait,San Mateo,4.7
10,11,111,2011,Language Classes,Immigrants,NaN,20,active,1 week,San Carlos,4.2
11,12,112,2012,Emergency Shelter,Homeless families,NaN,0,active,Immediate,Daly City,4.5
12,13,113,2013,Financial Literacy,Young adults,Age 18-30,15,active,2 weeks,Redwood City,4.1
13,14,114,2014,Child Care Support,Working parents,Employment proof,25,active,4 days,Belmont,4.0
14,15,115,2015,Substance Abuse Support,Adults 18+,Medical referral,40,inactive,2 weeks,San Mateo,3.7

In [ ]:
df =pd.read_csv('services_data.csv',header=None) #internal integer are provided by pandas
df

,0,1,2,3,4,5,6,7,8,9,10
0,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
1,1,101,2001,Food Assistance,Low income families,Income below poverty line,0,active,No wait,San Mateo,4.2
2,2,102,2002,Job Training,Unemployed adults,18+ age,50,active,2 weeks,Daly City,4.5
3,3,103,2003,Senior Care,Senior citizens,Age 60+,20,active,1 week,Redwood City,4.0
4,4,104,2004,Health Checkup,General public,NaN,10,active,3 days,Belmont,3.8
5,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3
6,6,106,2006,Housing Assistance,Homeless individuals,NaN,0,inactive,No wait,San Mateo,4.1
7,7,107,2007,Mental Health Counseling,Adults 18+,Appointment required,30,active,5 days,Daly City,4.6
8,8,108,2008,Legal Aid,Low income residents,Income verification,0,active,1 week,Redwood City,4.4
9,9,109,2009,Drug Rehabilitation,Adults 21+,Medical assessment,100,active,3 weeks,Belmont,3.9
10,10,110,2010,Community Meals,Senior citizens,Age 60+,5,active,No wait,San Mateo,4.7
11,11,111,2011,Language Classes,Immigrants,NaN,20,active,1 week,San Carlos,4.2
12,12,112,2012,Emergency Shelter,Homeless families,NaN,0,active,Immediate,Daly City,4.5
13,13,113,2013,Financial Literacy,Young adults,Age 18-30,15,active,2 weeks,Redwood City,4.1
14,14,114,2014,Child Care Support,Working parents,Employment proof,25,active,4 days,Belmont,4.0
15,15,115,2015,Substance Abuse Support,Adults 18+,Medical referral,40,inactive,2 weeks,San Mateo,3.7

In [3]:
df =pd.read_csv('services_data.csv',skiprows=2)
df

,2,102,2002,Job Training,Unemployed adults,18+ age,50,active,2 weeks,Daly City,4.5
0,3,103,2003,Senior Care,Senior citizens,Age 60+,20,active,1 week,Redwood City,4.0
1,4,104,2004,Health Checkup,General public,NaN,10,active,3 days,Belmont,3.8
2,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3
3,6,106,2006,Housing Assistance,Homeless individuals,NaN,0,inactive,No wait,San Mateo,4.1
4,7,107,2007,Mental Health Counseling,Adults 18+,Appointment required,30,active,5 days,Daly City,4.6
5,8,108,2008,Legal Aid,Low income residents,Income verification,0,active,1 week,Redwood City,4.4
6,9,109,2009,Drug Rehabilitation,Adults 21+,Medical assessment,100,active,3 weeks,Belmont,3.9
7,10,110,2010,Community Meals,Senior citizens,Age 60+,5,active,No wait,San Mateo,4.7
8,11,111,2011,Language Classes,Immigrants,NaN,20,active,1 week,San Carlos,4.2
9,12,112,2012,Emergency Shelter,Homeless families,NaN,0,active,Immediate,Daly City,4.5
10,13,113,2013,Financial Literacy,Young adults,Age 18-30,15,active,2 weeks,Redwood City,4.1
11,14,114,2014,Child Care Support,Working parents,Employment proof,25,active,4 days,Belmont,4.0
12,15,115,2015,Substance Abuse Support,Adults 18+,Medical referral,40,inactive,2 weeks,San Mateo,3.7

In [8]:
df =pd.read_csv('services_data.csv',usecols=['program_id','service_name'])
df

    program_id              service_name
0         2001           Food Assistance
1         2002              Job Training
2         2003               Senior Care
3         2004            Health Checkup
4         2005   Child Education Support
5         2006        Housing Assistance
6         2007  Mental Health Counseling
7         2008                 Legal Aid
8         2009       Drug Rehabilitation
9         2010           Community Meals
10        2011          Language Classes
11        2012         Emergency Shelter
12        2013        Financial Literacy
13        2014        Child Care Support
14        2015   Substance Abuse Support

In [4]:
df =pd.read_csv('services_data.csv')
df

,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
0,1,101,2001,Food Assistance,Low income families,Income below poverty line,0,active,No wait,San Mateo,4.2
1,2,102,2002,Job Training,Unemployed adults,18+ age,50,active,2 weeks,Daly City,4.5
2,3,103,2003,Senior Care,Senior citizens,Age 60+,20,active,1 week,Redwood City,4.0
3,4,104,2004,Health Checkup,General public,NaN,10,active,3 days,Belmont,3.8
4,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3
5,6,106,2006,Housing Assistance,Homeless individuals,NaN,0,inactive,No wait,San Mateo,4.1
6,7,107,2007,Mental Health Counseling,Adults 18+,Appointment required,30,active,5 days,Daly City,4.6
7,8,108,2008,Legal Aid,Low income residents,Income verification,0,active,1 week,Redwood City,4.4
8,9,109,2009,Drug Rehabilitation,Adults 21+,Medical assessment,100,active,3 weeks,Belmont,3.9
9,10,110,2010,Community Meals,Senior citizens,Age 60+,5,active,No wait,San Mateo,4.7
10,11,111,2011,Language Classes,Immigrants,NaN,20,active,1 week,San Carlos,4.2
11,12,112,2012,Emergency Shelter,Homeless families,NaN,0,active,Immediate,Daly City,4.5
12,13,113,2013,Financial Literacy,Young adults,Age 18-30,15,active,2 weeks,Redwood City,4.1
13,14,114,2014,Child Care Support,Working parents,Employment proof,25,active,4 days,Belmont,4.0
14,15,115,2015,Substance Abuse Support,Adults 18+,Medical referral,40,inactive,2 weeks,San Mateo,3.7

In [8]:
#Data structure >> Series and Data frame 
#Series>> One dimensional in nature
#DataFrame>> two dimensional in Nature, multiple series contitutes to form a Dataframe

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df['audience']

0      Low income families
1        Unemployed adults
2          Senior citizens
3           General public
4        Children age 6-14
5     Homeless individuals
6               Adults 18+
7     Low income residents
8               Adults 21+
9          Senior citizens
10              Immigrants
11       Homeless families
12            Young adults
13         Working parents
14              Adults 18+
Name: audience, dtype: object

In [7]:
type(df['audience'])

pandas.core.series.Series

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
l = [1,2,3,4]
s = pd.Series(l)
s

0    1
1    2
2    3
3    4
dtype: int64

In [10]:
type(s)

pandas.core.series.Series

In [11]:
s[2]

3

In [12]:
s[1]

2

In [13]:
s[2:4]

2    3
3    4
dtype: int64

In [22]:
s[2:]

2    3
3    4
dtype: int64

In [16]:
d = pd.Series([100,200,300],index = ["Adarsh","Dharmendra","Guddu"])
d

Adarsh        100
Dharmendra    200
Guddu         300
dtype: int64

In [17]:
type(d)

pandas.core.series.Series

In [18]:
d.index

Index(['Adarsh', 'Dharmendra', 'Guddu'], dtype='object')

In [19]:
d["Adarsh"]

100

In [20]:
d["Adarsh":"Guddu"]

Adarsh        100
Dharmendra    200
Guddu         300
dtype: int64

In [21]:
d.reset_index()

        index    0
0      Adarsh  100
1  Dharmendra  200
2       Guddu  300

In [22]:
d.reset_index(drop=True)

0    100
1    200
2    300
dtype: int64

In [23]:
pd.DataFrame(d)

              0
Adarsh      100
Dharmendra  200
Guddu       300

In [24]:
df

,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
0,1,101,2001,Food Assistance,Low income families,Income below poverty line,0,active,No wait,San Mateo,4.2
1,2,102,2002,Job Training,Unemployed adults,18+ age,50,active,2 weeks,Daly City,4.5
2,3,103,2003,Senior Care,Senior citizens,Age 60+,20,active,1 week,Redwood City,4.0
3,4,104,2004,Health Checkup,General public,NaN,10,active,3 days,Belmont,3.8
4,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3
5,6,106,2006,Housing Assistance,Homeless individuals,NaN,0,inactive,No wait,San Mateo,4.1
6,7,107,2007,Mental Health Counseling,Adults 18+,Appointment required,30,active,5 days,Daly City,4.6
7,8,108,2008,Legal Aid,Low income residents,Income verification,0,active,1 week,Redwood City,4.4
8,9,109,2009,Drug Rehabilitation,Adults 21+,Medical assessment,100,active,3 weeks,Belmont,3.9
9,10,110,2010,Community Meals,Senior citizens,Age 60+,5,active,No wait,San Mateo,4.7
10,11,111,2011,Language Classes,Immigrants,NaN,20,active,1 week,San Carlos,4.2
11,12,112,2012,Emergency Shelter,Homeless families,NaN,0,active,Immediate,Daly City,4.5
12,13,113,2013,Financial Literacy,Young adults,Age 18-30,15,active,2 weeks,Redwood City,4.1
13,14,114,2014,Child Care Support,Working parents,Employment proof,25,active,4 days,Belmont,4.0
14,15,115,2015,Substance Abuse Support,Adults 18+,Medical referral,40,inactive,2 weeks,San Mateo,3.7

In [25]:
df.shape

(15, 11)

In [26]:
df.columns

Index(['id', 'location', 'program_id', 'service_name', 'audience',
       'eligibility', 'fees', 'status', 'wait_time', 'city', 'rating'],
      dtype='object')

In [28]:
list(df.columns)

['id',
 'location',
 'program_id',
 'service_name',
 'audience',
 'eligibility',
 'fees',
 'status',
 'wait_time',
 'city',
 'rating']

In [29]:
df.head(5)

,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
0,1,101,2001,Food Assistance,Low income families,Income below poverty line,0,active,No wait,San Mateo,4.2
1,2,102,2002,Job Training,Unemployed adults,18+ age,50,active,2 weeks,Daly City,4.5
2,3,103,2003,Senior Care,Senior citizens,Age 60+,20,active,1 week,Redwood City,4.0
3,4,104,2004,Health Checkup,General public,NaN,10,active,3 days,Belmont,3.8
4,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3

In [30]:
df.tail(5)

,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
10,11,111,2011,Language Classes,Immigrants,NaN,20,active,1 week,San Carlos,4.2
11,12,112,2012,Emergency Shelter,Homeless families,NaN,0,active,Immediate,Daly City,4.5
12,13,113,2013,Financial Literacy,Young adults,Age 18-30,15,active,2 weeks,Redwood City,4.1
13,14,114,2014,Child Care Support,Working parents,Employment proof,25,active,4 days,Belmont,4.0
14,15,115,2015,Substance Abuse Support,Adults 18+,Medical referral,40,inactive,2 weeks,San Mateo,3.7

In [32]:
df.sample(1)

,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
4,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3

In [33]:
df

,id,location,program_id,service_name,audience,eligibility,fees,status,wait_time,city,rating
0,1,101,2001,Food Assistance,Low income families,Income below poverty line,0,active,No wait,San Mateo,4.2
1,2,102,2002,Job Training,Unemployed adults,18+ age,50,active,2 weeks,Daly City,4.5
2,3,103,2003,Senior Care,Senior citizens,Age 60+,20,active,1 week,Redwood City,4.0
3,4,104,2004,Health Checkup,General public,NaN,10,active,3 days,Belmont,3.8
4,5,105,2005,Child Education Support,Children age 6-14,School enrollment required,0,active,1 week,San Carlos,4.3
5,6,106,2006,Housing Assistance,Homeless individuals,NaN,0,inactive,No wait,San Mateo,4.1
6,7,107,2007,Mental Health Counseling,Adults 18+,Appointment required,30,active,5 days,Daly City,4.6
7,8,108,2008,Legal Aid,Low income residents,Income verification,0,active,1 week,Redwood City,4.4
8,9,109,2009,Drug Rehabilitation,Adults 21+,Medical assessment,100,active,3 weeks,Belmont,3.9
9,10,110,2010,Community Meals,Senior citizens,Age 60+,5,active,No wait,San Mateo,4.7
10,11,111,2011,Language Classes,Immigrants,NaN,20,active,1 week,San Carlos,4.2
11,12,112,2012,Emergency Shelter,Homeless families,NaN,0,active,Immediate,Daly City,4.5
12,13,113,2013,Financial Literacy,Young adults,Age 18-30,15,active,2 weeks,Redwood City,4.1
13,14,114,2014,Child Care Support,Working parents,Employment proof,25,active,4 days,Belmont,4.0
14,15,115,2015,Substance Abuse Support,Adults 18+,Medical referral,40,inactive,2 weeks,San Mateo,3.7

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            15 non-null     int64
 1   location      15 non-null     int64
 2   program_id    15 non-null     int64
 3   service_name  15 non-null     object
 4   audience      15 non-null     object
 5   eligibility   11 non-null     object
 6   fees          15 non-null     int64
 7   status        15 non-null     object
 8   wait_time     15 non-null     object
 9   city          15 non-null     object
 10  rating        15 non-null     float64
dtypes: float64(1), int64(4), object(6)
memory usage: 1.4+ KB

In [37]:
df.dtypes

id                int64
location          int64
program_id        int64
service_name     object
audience         object
eligibility      object
fees              int64
status           object
wait_time        object
city             object
rating          float64
dtype: object

In [38]:
df['id']

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
Name: id, dtype: int64

In [39]:
df['audience']

0      Low income families
1        Unemployed adults
2          Senior citizens
3           General public
4        Children age 6-14
5     Homeless individuals
6               Adults 18+
7     Low income residents
8               Adults 21+
9          Senior citizens
10              Immigrants
11       Homeless families
12            Young adults
13         Working parents
14              Adults 18+
Name: audience, dtype: object

In [40]:
type(df['audience'])

pandas.core.series.Series

In [42]:
list [df['audience']]

list[0      Low income families
1        Unemployed adults
2          Senior citizens
3           General public
4        Children age 6-14
5     Homeless individuals
6               Adults 18+
7     Low income residents
8               Adults 21+
9          Senior citizens
10              Immigrants
11       Homeless families
12            Young adults
13         Working parents
14              Adults 18+
Name: audience, dtype: object]